xych/main/forms.py
#!/usr/bin/env python
# coding=utf-8
from flask_pagedown.fields import PageDownField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError

from ..models import Role, User


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    # file = FileField(u'文件', validators=[FileRequired(),])
    submit = SubmitField('Submit')


class EditProfileForm(FlaskForm):
    name = StringField(u'真实姓名', validators=[Length(0, 64)])
    location = StringField(u'地区', validators=[Length(0,64)])
    about_me = TextAreaField(u'个人简介')
    submit = SubmitField(u'修改')


class EditProfileAdminForm(FlaskForm):
    email = StringField(u'邮箱', validators=[DataRequired(), Email(), Length(1, 64)])
    username = StringField(u'昵称', validators=[DataRequired(), Length(1,64),
                                              Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                u'昵称必须包含数字，字母或下划线')])
    confirmed = BooleanField(u'确认状态')
    role = SelectField(u'角色', coerce=int)
    name = StringField(u'真实姓名', validators=[Length(0, 64)])
    location = StringField(u'地区', validators=[Length(0,64)])
    about_me = TextAreaField(u'个人简介')
    submit = SubmitField(u'修改')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name) for role in
                             Role.query.order_by(Role.name).all()]

        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and\
            User.query.filter_by(email=field.data).first():
            raise ValidationError(u'邮箱已存在')


    def validate_username(self, field):
        if field.data != self.user.username and\
            User.query.filter_by(username=field.data).first():
            raise ValidationError(u'昵称已存在')

class PostForm(FlaskForm):
    body = PageDownField(u'正文', validators=[DataRequired()])
    submit = SubmitField(u'提交')

class CommentForm(FlaskForm):
    body = PageDownField(' ',  validators=[DataRequired()])
    submit = SubmitField(u'提交')

xych/__init__.py
#!/usr/bin/env python
# coding=utf-8
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_pagedown import PageDown
from flask_oauthlib.client import OAuth
from flask_oauthlib.provider import OAuth2Provider


from config import config


bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
loginmanager = LoginManager()
loginmanager.session_protection = 'strong'
loginmanager.login_view = 'auth.login'
loginmanager.login_message = u'请先登录'
pagedown = PageDown()
oauth = OAuth()
weibo = oauth.remote_app(
    'weibo',
    app_key='WEIBO'
)
oauth2server = OAuth2Provider()

def change_weibo_header(uri, headers, body):
    auth = headers.get('Authorization')
    if auth:
        auth = auth.replace('Bearer', 'OAuth2')
        headers['Authorization'] = auth
    return uri, headers, body

weibo.pre_request = change_weibo_header

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    loginmanager.init_app(app)
    pagedown.init_app(app)
    oauth.init_app(app)
    oauth2server.init_app(app)

    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    from .api_1_0 import api as api_1_0_blueprint
    from .api_1_1 import api as api_1_1_blueprint
    from .oauth2 import oauth2 as oauth2_blueprint

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(api_1_0_blueprint, url_prefix='/api/v1.0')
    app.register_blueprint(api_1_1_blueprint, url_prefix='/api/v1.1')
    app.register_blueprint(oauth2_blueprint, url_prefix='/oauth2')

    return app

xych/api_1_0/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from flask import Blueprint

api = Blueprint('api', __name__)

from . import authentication, posts, users, comments, errors

xych/api_1_1/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from flask import Blueprint

api = Blueprint('api_v1.1', __name__)


from . import posts, token

xych/api_1_1/auth.py
#!/usr/bin/env python
# encoding: utf-8

import re
import json
import base64

import jwt
from flask import current_app


def create_token(payload, alg='HS256'):
    SECRET_KEY = current_app.config.get('SECRET_KEY') or 'IJSOWC1U9NAF0NT'
    # 不传公共声明，payload不会自动添加公共声明
    # iat 时间需要为时间戳， 不要转换成13位整形(毫秒级)
    # jwt decode 会判断iat时间，exp时间
    #payload.update({
    #    'identity': user_id,
    #    'iat': now,
    #    'nbf': now,
    #    'exp': now + 60 * 60,
    #})
    return jwt.encode(payload, SECRET_KEY, algorithm=alg)

def parse_token(token):
    SECRET_KEY = current_app.config.get('SECRET_KEY') or 'IJSOWC1U9NAF0NT'
    try:
        if token.lower().startswith('jwt'):
            _, data = re.split(r'\s+', token)
            header, _, _ = data.split('.')
            alg = json.loads(base64.b64decode(header)).get('alg')

            # JWT decode 会自动判断payload中过期时间
            return jwt.decode(data, SECRET_KEY, algorithms=[alg])
    except Exception, e:
        print e
        current_app.logger.exception(e)

xych/main/__init__.py
#!/usr/bin/env python
# coding=utf-8
from flask import Blueprint

from .. models import Permission

main = Blueprint('main', __name__)

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

from . import views, errors

xych/main/views.py
#!/usr/bin/env python
# coding=utf-8
from datetime import datetime

from flask import (render_template, session,
                   redirect, url_for, flash, abort,
                   request, current_app, make_response, g)
from flask_login import login_required, current_user
from flask_sqlalchemy import get_debug_queries

from . import main
from .forms import  EditProfileForm, EditProfileAdminForm, PostForm, CommentForm
from .. import db
from ..models import User, Role, Permission, Post, Comment
from ..email import send_mail
from ..decorators import admin_required, permission_required

@main.route('/', methods=['GET', 'POST'])
def index():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        form.body.data = None
        return redirect(url_for('.index'))

    page = request.args.get('page', 1, type=int)
    show_followed = False
    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query

    pagination = query.order_by(Post.timestamp.desc()).paginate(
                page, per_page=current_app.config['POSTS_PER_PAGE'],
                error_out=False)
    posts = pagination.items

    res = {
        'form': form,
        'posts': posts,
        'pagination': pagination,
        'show_followed': show_followed
    }
    return render_template('index.html', **res)

@main.route('/user/<username>/')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('user.html', user=user, posts=posts)


@main.route('/edit-profile/', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash(u'个人信息已更改')
        return redirect(url_for('.user', username=current_user.username))

    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)

@main.route('/edit-profil/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
       user.email = form.email.data
       user.username = form.username.data
       user.confirmed = form.confirmed.data
       user.role = Role.query.get(form.role.data)
       user.name = form.name.data
       user.location = form.location.data
       user.about_me = form.about_me.data
       db.session.add(user)
       flash(u'个人资料已更新')
       return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        flash(u'编辑成功')
        return redirect(url_for('.post', id=post.id))

    form.body.data = post.body
    return render_template('edit_post.html', form=form)

@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('.index'))
    if current_user.is_following(user):
        flash(u'你已关注该用户')
        return redirect(url_for('.index'))
    current_user.follow(user)
    flash(u'你正在关注 %s' % username)
    return redirect(url_for('.user', username=username))

@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.queyr.filter_by(username=username).frist()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('.index'))
    if not current_user.is_following(user):
        flash(u'你尚未关注该用户')
        return redirect(url_for('.index'))
    current_user.unfollow(user)
    flash(u'你已取关 %s' % username)
    return redirect(url_for('.user', username=username))

@main.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(page,
        per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
               for item in pagination.items]
    print follows
    return render_template('followers.html', user=user, title=u"我的粉丝",
                           endpoint='.followers', pagination=pagination,
                           follows=follows)

@main.route('/followed_by/<username>')
def followed_by(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash(u'无效用户')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(page,
        per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('followers.html', user=user, title=u'我的关注',
                           endpoint='.followed_by', pagination=pagination,
                           follows=follows)


@main.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*60)
    return resp

@main.route('/followdd')
def show_followed():
    resp = make_response(redirect(url_for('.index')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)
    return resp

@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data, post=post,
                         author=current_user._get_current_object())
        db.session.add(comment)
        flash(u'评论已提交')
        return redirect(url_for('.post', id=post.id, page=-1))

    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / current_app.config['COMMENTS_PER_PAGE'] + 1

    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items

    res = {
        'posts': [post],
        'form': form,
        'comments': comments,
        'pagination': pagination
    }
    return render_template('post.html', **res)

@main.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page',1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'], error_out=False)

    comments = pagination.items
    return render_template('moderate.html', comments=comments, pagination=pagination,
                          page=page)

@main.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))


@main.route('/moderate/disabled/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))

@main.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= current_app.config['SLOW_DB_QUERY_TIME']:
            current_app.logger.warning(
                'Slow query: %s\nParameters: %s\nDuration: %fs\nContext: %s\n' %(
                    query.statement, query.parameters, query.duration, query.context
                )
                )

    return response

xych/oauth2/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

oauth2 = Blueprint('oauth2', __name__)

xych/templates/_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-thumbnail">
            <a href="{{ url_for('.user', username=comment.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="comment-author"><a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a></div>
            <div class="comment-body">
                {% if comment.disabled %}
                <p><i>该评论被管理员禁用</i></p>
                {% endif %}
                {% if moderate or not comment.disabled %}
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
                {% endif %}
            </div>
            {% if moderate %}
                <br>
                {% if comment.disabled %}
                <a class="btn btn-default btn-xs" href="{{ url_for('.moderate_enable', id=comment.id, page=page) }}">启用</a>
                {% else %}
                <a class="btn btn-danger btn-xs" href="{{ url_for('.moderate_disable', id=comment.id, page=page) }}">禁用</a>
                {% endif %}
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

xych/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
  <li {% if not pagination.has_prev %} class="disabled" {% endif %}>
    <a href="{% if pagination.has_prev %}{{url_for(endpoint, page=pagination.prev_num, **kwargs) }}
    {% else %}#{% endif %}" >&laquo;</a> 
  </li>
  {% for p in pagination.iter_pages() %}
    {% if p%}
      <li {% if p == pagination.page %}class="active"{% endif %}>
        <a href="{{ url_for(endpoint, page=p, **kwargs)}}">{{ p }}</a>
      </li>
    {% else %}
      <li class="disabled"><a href="#">&hellip;</a></li>
    {% endif %}
  {% endfor %}
  <li {% if not pagination.has_next %} class="disabled" {% endif %}>
    <a href="{% if pagination.has_next %} {{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">&raquo;</a>
  </li>
</ul>
{% endmacro %}

xych/templates/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="profile-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail"
                src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-date">
            {{ moment(post.timestamp).fromNow() }}
        </div>
        <div class="post-author">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
        </div>
        <div class="post-body">
          {% if post.body_html %}
            {{ post.body_html|safe }}
          {% else %}
            {{ post.body }}
          {% endif%}
        </div>
        <div class="post-content">
          <div class="post-footer">
            <a href="{{ url_for('.post', id=post.id) }}">
              <span class="label label-default">链接</span>
            </a>
            {% if current_user == post.author %}
            <a href="{{ url_for('.edit', id=post.id) }}">
              <span class="label label-primary">编辑</span>
            </a>
            {% elif current_user.is_administrator() %}
            <a href="{{ url_for('.edit', id=post.id) }}">
              <span class="label label-primary">编辑[管理员]</span>
            </a>
            {% endif %}
            <a href="{{ url_for('.post', id=post.id) }}">
                <span class="label label-primary">{{ post.comments.count() }}个评论</span>
            </a>
          </div> 
        </div>
    </li>
    {% endfor %}
</ul>

xych/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}Flasky{% endblock %}
{% block head %}
{{ super()  }}
<link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon.ico')  }}"
                          type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename = 'favicon.ico')  }}"
                 type="image/x-icon">
<link rel="StyleSheet" href="{{ url_for('static', filename='styles.css')}}">
{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle"
data-toggle="collapse" data-target=".navbar-collapse">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">星宇晨辉</a>
</div>
<div class="navbar-collapse collapse">
<ul class="nav navbar-nav">
<li><a href="/">首页</a></li>
{% if current_user.is_authenticated %}
<li><a href="{{ url_for('main.user', username=current_user.username) }}">个人资料</a></li>
{% endif %}
{% if current_user.can(Permission.MODERATE_COMMENTS) %}
<li> <a href="{{ url_for('main.moderate') }}">修改评论</a><li>
{% endif %}
</ul>

<ul class="nav navbar-nav navbar-right">
   {% if not current_user.is_authenticated %}
   <li><a href="{{ url_for('auth.login') }}">登录</a></li>
   {% else %}
   <li class="dropdown"><a href="#" class="drodown-toggle" data-toggle="dropdown">
       账号<b class="caret"></b>
   </a>
   <ul class="dropdown-menu">
       <li><a href="{{ url_for('auth.modify_password') }}">修改密码</a></li>
       <li><a href="{{ url_for('auth.change_email') }}">修改邮箱</a></li>
       <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
   </li>
   </ul>
   {% endif %}
</ul>
</div>
</div>
</div>
{% endblock %}
{% block content %}
<div class="container">
{% for message in get_flashed_messages() %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% block page_content %}{% endblock %}
</div>
{% endblock %}
{% block scripts %}
{{ super()  }}
{{ moment.include_moment()  }}
{{ moment.locale('zh-cn') }}
{% endblock %}

xych/templates/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}星雨晨辉 - 编辑正文 {% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>编辑正文</h1> 
</div>
<div>
    {{ wtf.quick_form(form) }} 
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

xych/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}星宇晨辉 - 编辑资料{% endblock %}
{% block page_content %}
<div class="page-header">
<h1>编辑资料</h1> <p>
</div>
<div class="col-md-4">
{{ wtf.quick_form(form) }}
</div>
{% endblock %}

xych/templates/followers.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %} 星宇晨辉 - {{ title }} {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ title }} {{ user.username }}</h1>
</div>
<table class="table table-hover followers">
    <thead><tr><th>用户</th><th>时间</th></tr></thead>
    {% for follow in follows %}
    {% if follow.user != user %}
    <tr>
        <td>
            <a href="{{ url_for('.user', username = follow.user.username) }}">
                <img class="img-rounded" src="{{ follow.user.gravatar(size=32) }}">
                {{ follow.user.username }}
            </a>
        </td>
        <td>{{ moment(follow.timestamp).format('L') }}</td>
    </tr>
    {% endif %}
    {% endfor %}
</table>
<div class="pagination">
    {{ macros.pagination_widget(pagination, endpoint, username = user.username) }}
</div>
{% endblock %}

xych/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}
星宇晨辉
{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Hello 
        {% if current_user.is_authenticated %}
        {{ current_user.username }}
        {% else %}
        访客
        {% endif %}
        </h1>
    <div>
        {% if current_user.can(Permission.WRITE_ARTICLES) %}
        {{ wtf.quick_form(form) }}
        {% endif %}
    </div>
    <div class="post-tabs">
        <ul class="nav nav-tabs">
            <li {% if not show_followed %} class="active" {% endif %}>
                <a href="{{ url_for('.show_all') }}">全部</a>
            </li>
            {% if current_user.is_authenticated %}
            <li {% if show_followed %} class="active" {% endif %}>
                <a href="{{ url_for('.show_followed') }}">关注的人</a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>
{% include '_posts.html' %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

xych/templates/moderate.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}星宇晨辉 - 评论管理{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>管理评论</h1>
</div>
{% set moderate = True %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.moderate') }}
</div>
{% endif %}
{% endblock %}

xych/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}星雨晨辉 - 正文{% endblock %}
{% block page_content %}
{% include '_posts.html' %}
<h4 id="comments">评论</h4>
{% if current_user.can(Permission.COMMENT) %}
<div class="comment-form">
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
{% include '_comments.html' %}
{% if pagination %}
{{ macros.pagination_widget(pagination, '.post', fragment='#comments', id=posts[0].id) }}
{% endif %}
{% endblock %}
{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

xych/templates/user.html
{% extends "base.html" %}

{% block title %}
星宇晨辉 - 个人资料
{% endblock %}

{% block page_content %}
<div class='page-header'>
    <img class="img-round profile-thumbnail" src="{{ user.gravatar(size=256)}}">
    <div class="profile-header">
    <h1>{{  user.username }}</h1>
    {% if user.name or user.location %}
    <p>
    {% if user.name %}{{  user.name  }}{% endif %}
    {% if user.location %}
    来自<a href="http://maps.google.com/?q={{ user.location  }}">{{ user.location }}</a>
    {% endif %}
    </p>
    {% endif %}
    {% if current_user.is_administrator() %}
    <p><a href="mailto:{{ user.email }}">{{  user.email }}</a></p>
    {% endif %}
    {% if user.about_me %}<p>{{ user.about_me }}{% endif %}</p>
    <p>
    注册时间：{{ moment(user.member_since).format('LL') }}, 
    上次登录：{{ moment(user.last_seen).fromNow() }}
    </p>
    <p>
    {% if user == current_user %}
    <a class="btn btn-default" href="{{ url_for('.edit_profile')}}" arget="_Blank">编辑个人资料</a>
    {% endif %}
    {% if current_user.is_administrator() %}
        <a class="btn btn-danger" href="{{ url_for('.edit_profile_admin', id=user.id)}}" arget="_Blank">编辑个人资料[管理员]</a>
    {% endif %}
    </p>
    {% if current_user.can(Permission.FOLLOW) and current_user != user %}
        {% if not current_user.is_following(user) %}
        <a href="{{ url_for('.follow', username=user.username) }}" class="btn btn-primary">关注</a>
        {% else %}
        <a href="{{ url_for('.unfollow', username=user.username) }}" class="btn btn-default">取关</a>
        {% endif %}
    {% endif %}
    <a href="{{ url_for('.followers', username=user.username) }}">
        粉丝： <span class="badge">{{ user.followers.count() - 1 }}</span>
    </a>|
    <a href="{{ url_for('.followed_by', username=user.username) }}">
        关注： <span class="badge">{{ user.followed.count() - 1 }}</span>
    </a>
    {% if current_user.is_administrator() and current_user != user and user.is_following(current_user) %}
       | <span class="label label-default">关注我</span> 
    {% endif %}
    </div>
    <h3>{{ user.username }} 发布：</h3>
    {% include '_posts.html' %}

</div>

{% endblock %}